---
title: Instalación de módulos de Python con pip
hero_image: images/banner.png
description: Instalación de módulos de Python con pip
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "python"
site_areas:
steps:
  - 
    title: Instalación de módulos de Python
